default: &default
  docker:
    - image: circleci/node:8.4.0
  working_directory: ~/sms  
restore_cache: &restore_cache
  restore_cache:
    key: dependency-cache-{{ checksum "package.json" }}
install_dependencies: &install_dependencies  
  run:
    name: install dependencies
    command: npm install
save_cache: &save_cache 
  save_cache:
    key: dependency-cache-{{ checksum "package.json"}}
    paths:
      - ./node_modules 

version: 2
jobs:
  build:
    <<: *default
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache 
      - run: 
          name: install dependancies
          command: npm install 
  tests: 
    <<: *default
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run:
          name: run tests
          command: npm run test
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: submit coverage reports
          command: npm run coveralls

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - tests
          # requires:
          #   - build          

